# Default values for cdp-rewardcatalogue PROD.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: prod

# ingress controls
ingress:
  name: cdp-rewardcatalogue-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: kz-gift.hostname.com
  secretName: hostname-com-tls
  path: "/"
  className: internal-nginx

image:
  repository: cemulkerefe/cdp-rewardcatalogue
  tag: latest

elasticconfiguration_uri: "https://prod.es.westeurope.azure.elastic-cloud.com/"
elasticconfiguration_username: "logger"
elasticconfiguration_password: "000000000"
isapikeyenabled: "false"
