# Default values for cdp-rewardcatalogue.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common controls
environment: dev
application: cdp-rewardcatalogue
containerPort: 80
size: medium

# Service controls
service:
  name: cdp-rewardcatalogue-svc
  type: ClusterIP
  port: 80

hpa:
  min: 1
  max: 3
  cpu: 75
  memory: 75

# ingress controls
ingress:
  name: cdp-rewardcatalogue-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: cdp-rewardcatalogue-dev.11.11.111.111.nip.io
  secretName: cdp-rewardcatalogue-tls
  path: "/"

# Deployment controls
restartPolicy: Always

replicas: 1
resources:
  requests:
    cpu: 150m
    memory: 500Mi
  limits:
    cpu: 500m
    memory: 2Gi

image:
  imagePullSecret: regcred
  repository: cemulkerefe/cdp-rewardcatalogue
  tag: latest

registrySecret:
  name: acr-registry
  config: { "auths": { "docker.io": { "auth": "" } } }
