apiVersion: v1
kind: Secret
metadata:
  name: sec-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  new-relic-license-key: "{{ .Values.new_relic_license_key }}" 