# Default values for cdp-service PROD.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: prod

# ingress controls
ingress:
  name: cdp-service-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: kz-cdp-service-local.hostname.com
  secretName: hostname-com-tls
  path: "/"
  className: internal-nginx

image:
  repository: cemulkerefe/cdp-service
  tag: latest

fletum_api_base_url: https://prod-api.azurewebsites.net
create_entity_base_url: https://prod-api.azurewebsites.net
validation_microservice_base_url: http://validation-service-svc-prod:8010
identity_microservice_base_url: http://identity-service-svc-prod:8989
otp_service_base_url: http://otp-service-svc-prod:8089
cep_module_base_url: http://cep-module-svc-prod.prod-integration.svc:7070
connection_string_default_conn: "Data Source=11.11.111.111;Initial Catalog=CDPKZProd;Persist Security Info=True;User ID=cdpkzproduser;Password=000000;MultipleActiveResultSets=True;Application Name=cdp-service-prod"
connection_string_staging_conn: "Data Source=11.11.111.111;Initial Catalog=CDPKZProdIntegration;Persist Security Info=True;User ID=cdpkzprodintegrationuser;Password=000000;MultipleActiveResultSets=True;Application Name=cdp-service-prod"
fletum_web_base_url: https://prod-web.azurewebsites.net
applicationinsights_instrumentationkey: 00000-0000-0000-0000-00000
cciordersecuritykey: cci
voyageorderurl: https://kz-order.hostname.com/Member/LoginByToken?
elasticconfiguration_uri: "https://prod.es.westeurope.azure.elastic-cloud.com/"
elasticconfiguration_username: "logger-cdp"
elasticconfiguration_password: "000000000"
isapikeyenabled: "false"

serilogminimumlevel: "Info"
IsCache: "false"
jwt_configuration_security_key: "4cd5d3c088ca102a24bad8339b4dd06c7964a1f05c54d9cb48e1dc710146b722"

CacheTimespan: "10"

hpa:
  min: 6
  max: 7
  cpu: 75
  memory: 75

QueueSize: "500"
QueueDelay: "100"
QueueEnabled: "true"

logminimumlevel: INFO
new_relic_app_name: cdp-service-prod

livenessProbe:
  enabled: true
  httpGet:
    path: "/swagger/index.html"
    port: 5500
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
readinessProbe:
  enabled: true
  httpGet:
    path: "/swagger/index.html"
    port: 5500
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
