# Default values for kafka-create-item PREPROD.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: preprod

# ingress controls
ingress:
  name: kafka-create-item-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: kafka-create-item-preprod.11.111.111.11.nip.io
  secretName: kafka-create-item-tls
  path: "/"

image:
  repository: cemulkerefe/kafka-create-item
  tag: latest

spring_kafka_bootstrap_servers: kafka-cluster-preprod-kafka-bootstrap.cdp-preprod-kafka.svc:9092
fletum_api_url: https://cdp-preprod-api.azurewebsites.net
applicationinsights_instrumentationkey: 0000000-0000-4ff3-0000-00000008
elasticconfiguration_uri: "https://elk-preprod.es.westeurope.azure.elastic-cloud.com:443"
elasticconfiguration_username: "logger"
elasticconfiguration_password: "0080000H0000x"
elasticconfiguration_kb_uri: "https://elk-preprod.kb.westeurope.azure.elastic-cloud.com:443"
elasticconfiguration_kb_username: "logger"
elasticconfiguration_kb_password: "0080000H0000x"
isapikeyenabled: "false"
item_service_url: "http://item-service-svc-preprod.preprod-integration.svc:8090"
logging_level_root: "Error"
