# Default values for kafka-create-item DEV.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: dev

# ingress controls
ingress:
  name: kafka-create-item-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: dev-kz-cdp-kafka-create-item-local.hostname.com
  secretName: kafka-create-item-tls
  path: "/"
  className: internal-nginx

image:
  repository: cemulkerefe/kafka-create-item
  tag: latest

spring_kafka_bootstrap_servers: kafka-cluster-dev-kafka-bootstrap.cdp-dev-kafka.svc:9092
fletum_api_url: https://dev-fletum-api.azurewebsites.net
applicationinsights_instrumentationkey: 00000-0000-0000-0000-e0273a105a61
elasticconfiguration_uri: "https://elk-dev.es.westeurope.azure.elastic-cloud.com:443"
elasticconfiguration_username: "logger"
elasticconfiguration_password: "password"
elasticconfiguration_kb_uri: "https://elk-dev.kb.westeurope.azure.elastic-cloud.com:443"
elasticconfiguration_kb_username: "logger"
elasticconfiguration_kb_password: "password"
isapikeyenabled: "true"
item_service_url: "http://item-service-svc-dev:8090"
logging_level_root: "Error"
