apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
data:
  urls: "{{ .Values.urls }}"
  smtp_settings_server: "{{ .Values.smtp_settings_server }}"
  smtp_settings_port: "{{ .Values.smtp_settings_port }}"
  smtp_settings_isssl: "{{ .Values.smtp_settings_isssl }}"
  smtp_settings_email: "{{ .Values.smtp_settings_email }}"
  smpp_settings_systemid: "{{ .Values.smpp_settings_systemid }}"
  smpp_settings_port: "{{ .Values.smpp_settings_port }}"
  smpp_settings_host: "{{ .Values.smpp_settings_host }}"
  sms_settings_url: "{{ .Values.sms_settings_url }}"
  sms_settings_channel_code: "{{ .Values.sms_settings_channel_code }}"
  sms_settings_user_name: "{{ .Values.sms_settings_user_name }}"
  kz_sms_settings_user_name: "{{ .Values.kz_sms_settings_user_name }}"
  kz_sms_settings_id: "{{ .Values.kz_sms_settings_id }}"
  kz_sms_settings_sender: "{{ .Values.kz_sms_settings_sender }}"
  applicationinsights-instrumentationkey: "{{ .Values.applicationinsights_instrumentationkey }}"
  services-fletumurl: "{{ .Values.services_fletumurl}}"
  elasticconfiguration-uri: "{{ .Values.elasticconfiguration_uri }}"
  elasticconfiguration-username: "{{ .Values.elasticconfiguration_username }}"
  isapikeyenabled: "{{ .Values.isapikeyenabled }}"
  serilogminimumlevel: "{{ .Values.serilogminimumlevel }}"
  country: "{{ .Values.country }}"
  product_name: "{{ .Values.product_name }}"
  app_name: "{{ .Values.app_name }}"
  elasticconfiguration-port: "{{ .Values.elasticconfiguration_port }}"
  elasticconfiguration-scheme: "{{ .Values.elasticconfiguration_scheme }}"
  Log-CustomerId: "{{ .Values.logcustomerid }}"
  Log-ApplicationName: "{{ .Values.logapplicationname }}"
  Log-ComponentName: "{{ .Values.logcomponentname }}"
  Log-ProductName: "{{ .Values.logproductname }}"
  Log-Country: "{{ .Values.logcountry }}"
  Log-MinimumLevel: "{{ .Values.logminimumlevel }}"
  new-relic-app-name: "{{ .Values.new_relic_app_name }}"  