apiVersion: v1
kind: Secret
metadata:
  name: sec-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  connection_string: "{{ .Values.connection_string }}"
  smtp_settings_password: "{{ .Values.smtp_settings_password }}"
  smpp_settings_password: "{{ .Values.smpp_settings_password }}"
  sms_settings_password: "{{ .Values.sms_settings_password }}"
  kz_sms_settings_password: "{{ .Values.kz_sms_settings_password }}"
  elasticconfiguration-password: "{{ .Values.elasticconfiguration_password }}"
  new-relic-license-key: "{{ .Values.new_relic_license_key }}" 

#data:
#  key1: value1 #base64encoded
#  key2: value2 #base64encoded