# Default values for azure-storage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common controls
environment: dev
application: azure-storage
containerPort: 9020
size: medium

# Service controls
service:
  name: azure-storage-svc
  type: ClusterIP
  port: 9020

hpa:
  min: 1
  max: 3
  cpu: 75
  memory: 75

# ingress controls
ingress:
  name: azure-storage-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: azure-storage-dev.11.11.111.111.nip.io
  secretName: azure-storage-tls
  path: "/"

# Deployment controls
restartPolicy: Always

replicas: 1
resources:
  requests:
    cpu: 150m
    memory: 500Mi
  limits:
    cpu: 500m
    memory: 1Gi

image:
  imagePullSecret: regcred
  repository: cemulkerefe/db-connector
  tag: latest

# liveness-readness
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

country: KZ
product_name: CDP
app_name: cdp-storage

# ConfigMap controls
urls: http://0.0.0.0:9020

new_relic_license_key:
elasticconfiguration_port: 443
elasticconfiguration_scheme: https
logcustomerid: efectura
logproductname: cdp
logcountry: kz
logcomponentname: service
logapplicationname: storage

registrySecret:
  name: acr-registry
  config: { "auths": { "docker.io": { "auth": "" } } }
