# Default values for azure-storage PREPROD.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: preprod

# ingress controls
ingress:
  name: azure-storage-ing
  pullPolicy: Always
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: preprod-kz-cdp-azure-storage-local.hostname.com
  secretName: hostname-wildcard-tls-preprod-app-ns
  path: "/"
  className: internal-nginx

image:
  repository: cemulkerefe/azure-storage
  tag: latest
  pullPolicy: Always

fletumapiurl: https://preprod-api.azurewebsites.net/api/
fletumweburl: https://preprod-ui.azurewebsites.net
connectionstrings_defaultconnection: DefaultEndpointsProtocol=https;AccountName=cdppreprodstorage;AccountKey=qXQL9CNCTKJqsSK3AQL1QM2+iIPLDi1hfTIJzqQHAJ3lgYox/eQE/fmqH0n+OUPSMmQqq2iEVkRuTeEc0btK+A==;EndpointSuffix=core.windows.net
azurestoragekey: qXQL9CNCTKJqsSK3AQL1QM2+iIPLDi1hfTIJzqQHAJ3lgYox/eQE/fmqH0n+OUPSMmQqq2iEVkRuTeEc0btK+A==
elasticconfiguration_uri: "elk-preprod.es.westeurope.azure.elastic-cloud.com"
elasticconfiguration_username: "logger"
elasticconfiguration_password: "0080000H0000x"
isapikeyenabled: "false"
serilogminimumlevel: "Error"

logminimumlevel: INFO
new_relic_app_name: azure-storage-service-kz-preprod

livenessProbe:
  enabled: true
  httpGet:
    path: "/swagger/index.html"
    port: 9020
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
readinessProbe:
  enabled: true
  httpGet:
    path: "/swagger/index.html"
    port: 9020
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
