apiVersion: v1
kind: Secret
metadata:
  name: sec-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  elasticconfiguration-password: "{{ .Values.elasticconfiguration_password }}"
  connection-string-default-conn: "{{ .Values.connection_string_default_conn }}"
  new-relic-license-key: "{{ .Values.new_relic_license_key }}"