apiVersion: v1
kind: Secret
metadata:
  name: sec-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
   connectionstrings_defaultconnection: "{{ .Values.connectionstrings_defaultconnection }}"
   azurestoragekey: "{{ .Values.azurestoragekey }}"
   elasticconfiguration-password: "{{ .Values.elasticconfiguration_password }}"
   new-relic-license-key: "{{ .Values.new_relic_license_key }}" 