# Default values for job-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common controls
environment: dev
application: job-service
containerPort: 8097
size: medium

# Service controls
service:
  name: job-service-svc
  type: ClusterIP
  port: 8097

# ingress controls
ingress:
  name: job-service-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: job-service-dev.11.11.111.111.nip.io
  secretName: job-service-tls
  path: "/"

# Deployment controls
restartPolicy: Always

replicas: 1
resources:
  requests:
    cpu: 150m
    memory: 500Mi
  limits:
    cpu: 500m
    memory: 1Gi

image:
  imagePullSecret: regcred
  repository: cemulkerefe/job-service
  tag: latest

# ConfigMap controls
urls: http://0.0.0.0:8097
services_jobserviceurl: http://0.0.0.0:8097/api/info
project_name: CDP
connectionstrings_database: Hangfire.db

registrySecret:
  name: acr-registry
  config: { "auths": { "docker.io": { "auth": "" } } }
