# Default values for job-service prod.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: prod

# ingress controls
ingress:
  name: job-service-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: job-service-prod.0.0.0.0.nip.io
  secretName: job-service-tls
  path: "/"
  className: internal-nginx

image:
  repository: cemulkerefe/job-service
  tag: latest

isapikeyenabled: "false"
