# Default values for search-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common controls
environment: dev
application: search-service
containerPort: 9201
size: medium

# Service controls
service:
  name: search-service-svc
  type: ClusterIP
  port: 9201

hpa:
  min: 1
  max: 10
  cpu: 75
  memory: 75

# ingress controls
ingress:
  name: search-service-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: search-service-dev.11.11.111.111.nip.io
  secretName: search-service-tls
  path: "/"

# Deployment controls
restartPolicy: Always

replicas: 1
resources:
  requests:
    cpu: 150m
    memory: 500Mi
  limits:
    cpu: 500m
    memory: 1Gi

image:
  imagePullSecret: regcred
  repository: cemulkerefe/search-service
  tag: latest

# ConfigMap controls
urls: http://0.0.0.0:9201

registrySecret:
  name: acr-registry
  config: { "auths": { "docker.io": { "auth": "" } } }
