# Default values for search-service PREPROD.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: preprod

# ingress controls
ingress:
  name: search-service-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: search-service-prep.0.0.0.0.nip.io
  secretName: search-service-tls
  path: "/"

image:
  repository: cemulkerefe/search-service
  tag: latest

applicationinsights_instrumentationkey: 0000000-0000-4ff3-0000-00000008
elasticconfiguration_uri: "https://elk-qa.es.westeurope.azure.elastic-cloud.com/"
elasticconfiguration_username: "logger"
elasticconfiguration_password: "password"
isapikeyenabled: "false"
serilogminimumlevel: "Error"
