# Default values for otp-service DEV.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: dev

# ingress controls
ingress:
  name: otp-service-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: dev-kz-cdp-otp-service-local.hostname.com
  secretName: hostname-wildcard-tls-cdp-dev-app-ns
  path: "/"
  className: internal-nginx

image:
  repository: cemulkerefe/otp-service
  tag: dev
  pullPolicy: Always

applicationinsights_instrumentationkey: 00000-0000-0000-0000-e0273a105a61
connection_string: "Data Source=11.111.11.111;Initial Catalog=CDPDev;Persist Security Info=True;User ID= cdpdevuser;Password=123456;MultipleActiveResultSets=True;"
services_fletumurl: https://dev-fletum-api.azurewebsites.net/api/
elasticconfiguration_uri: "elk-dev.es.westeurope.azure.elastic-cloud.com"
elasticconfiguration_username: "logger"
elasticconfiguration_password: "password"
isapikeyenabled: "true"
serilogminimumlevel: "Error"

elasticconfiguration_port: 443
elasticconfiguration_scheme: https
logcustomerid: efectura
logproductname: fletum

logminimumlevel: INFO
new_relic_app_name:
new_relic_license_key:

livenessProbe:
  enabled: true
  httpGet:
    path: "/swagger/index.html"
    port: 8089
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
readinessProbe:
  enabled: true
  httpGet:
    path: "/swagger/index.html"
    port: 8089
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
