apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
data:
  postgres_db: "{{ .Values.postgres_db }}"
  postgres_user: "{{ .Values.postgres_user }}"
  elasticconfiguration-uri: "{{ .Values.elasticconfiguration_uri }}"
  elasticconfiguration-username: "{{ .Values.elasticconfiguration_username }}"
  isapikeyenabled: "{{ .Values.isapikeyenabled }}"