apiVersion: v1
kind: Secret
metadata:
  name: sec-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  postgres_password: "{{ .Values.postgres_password }}"
  elasticconfiguration-password: "{{ .Values.elasticconfiguration_password }}"