# Default values for file-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common controls
environment: dev
application: file-connector
containerPort: 7050
size: medium

# Service controls
service:
  name: file-connector-svc
  type: ClusterIP
  port: 7050

hpa:
  min: 1
  max: 10
  cpu: 75
  memory: 75

# ingress controls
ingress:
  name: file-connector-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: file-connector-dev.11.11.111.111.nip.io
  secretName: file-connector-tls
  path: "/"

# Deployment controls
restartPolicy: Always

replicas: 1
resources:
  requests:
    cpu: 150m
    memory: 500Mi
  limits:
    cpu: 500m
    memory: 1Gi

image:
  imagePullSecret: regcred
  repository: cemulkerefe/file-connector
  tag: latest

country: kz
product_name: cdp
app_name: file-connector

registrySecret:
  name: acr-registry
  config: { "auths": { "docker.io": { "auth": "" } } }

new_relic_license_key:
elasticconfiguration_port: 443
elasticconfiguration_scheme: https
logcustomerid: efectura
logproductname: cdp
logcountry: kz
logcomponentname: connector
logapplicationname: file

# liveness-readness
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
