# Default values for csv-service PREPROD.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: kz-preprod

# ingress controls
ingress:
  name: file-connector-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: preprod-kz-cdp-file-connector-local.hostname.com
  secretName: hostname-wildcard-tls-preprod-integration-ns
  path: "/"
  className: internal-nginx

image:
  repository: cemulkerefe/file-connector
  tag: latest

spring_kafka_bootstrap_servers: kafka-cluster-kz-preprod-kafka-bootstrap.preprod-kafka.svc:9092
applicationinsights_instrumentationkey: 0000000-0000-4ff3-0000-000000000
elasticconfiguration_uri: "https://elk-preprod.es.westeurope.azure.elastic-cloud.com:443"
elasticconfiguration_username: "logger"
elasticconfiguration_password: "0080000H0000x"
elasticconfiguration_kb_uri: "https://elk-preprod.kb.westeurope.azure.elastic-cloud.com:443"
elasticconfiguration_kb_username: "logger"
elasticconfiguration_kb_password: "0080000H0000x"
isapikeyenabled: "false"
serilogminimumlevel: "Error"

logminimumlevel: INFO
new_relic_app_name: fileconnector-service-kz-preprod

livenessProbe:
  enabled: true
  httpGet:
    path: "/swagger-ui.html"
    port: 7050
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
readinessProbe:
  enabled: true
  httpGet:
    path: "/swagger-ui.html"
    port: 7050
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
