apiVersion: v1
kind: Secret
metadata:
  name: sec-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  connection-string-default-conn: "{{ .Values.connection_string_default_conn }}"
  connection-string-staging-conn: "{{ .Values.connection_string_staging_conn }}"
  telegram-chatid: "{{ .Values.telegram_chatid }}"
  telegram-key: "{{ .Values.telegram_key }}"
  elasticconfiguration-password: "{{ .Values.elasticconfiguration_password }}"
  jwt-configuration-security-key: "{{ .Values.jwt_configuration_security_key }}" 
  new-relic-license-key: "{{ .Values.new_relic_license_key }}"

#data:
#  key1: value1 #base64encoded
#  key2: value2 #base64encoded