apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
data:
  urls: "{{ .Values.urls }}"
  jwt-configuration-issuer: "{{ .Values.jwt_configuration_issuer }}"
  jwt-configuration-audience: "{{ .Values.jwt_configuration_audience }}"
  smtp-server: "{{ .Values.smtp_server }}"
  smtp-port: "{{ .Values.smtp_port }}"
  isssl: "{{ .Values.isssl }}"
  smtp-email: "{{ .Values.smtp_email }}"
  fletumapiurl: "{{ .Values.fletumapiurl }}"
  application-url: "{{ .Values.application_url }}"
  applicationinsights-instrumentationkey: "{{ .Values.applicationinsights_instrumentationkey }}"
  elasticconfiguration-uri: "{{ .Values.elasticconfiguration_uri }}"
  elasticconfiguration-username: "{{ .Values.elasticconfiguration_username }}"
  isapikeyenabled: "{{ .Values.isapikeyenabled }}"
  serilogminimumlevel: "{{ .Values.serilogminimumlevel }}"
  country: "{{ .Values.country }}"
  product_name: "{{ .Values.product_name }}"
  app_name: "{{ .Values.app_name }}"
  elasticconfiguration-port: "{{ .Values.elasticconfiguration_port }}"
  elasticconfiguration-scheme: "{{ .Values.elasticconfiguration_scheme }}"
  Log-CustomerId: "{{ .Values.logcustomerid }}"
  Log-ApplicationName: "{{ .Values.logapplicationname }}"
  Log-ComponentName: "{{ .Values.logcomponentname }}"
  Log-ProductName: "{{ .Values.logproductname }}"
  Log-Country: "{{ .Values.logcountry }}"
  Log-MinimumLevel: "{{ .Values.logminimumlevel }}"
  new-relic-app-name: "{{ .Values.new_relic_app_name }}"  