apiVersion: v1
kind: Secret
metadata:
  name: sec-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  connection-string-default-conn: "{{ .Values.connection_string_default_conn }}"
  jwt-configuration-security-key: "{{ .Values.jwt_configuration_security_key }}"
  elasticconfiguration-password: "{{ .Values.elasticconfiguration_password }}"
  smtp-password: "{{ .Values.smtp_password }}"
  new-relic-license-key: "{{ .Values.new_relic_license_key}}" 
#data:
#  key1: value1 #base64encoded
#  key2: value2 #base64encoded