apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
data:
  db_driver: "{{ .Values.db_driver }}"
  db_url: "{{ .Values.db_url }}"
  db_username: "{{ .Values.db_username }}"
  elasticconfiguration-uri: "{{ .Values.elasticconfiguration_uri }}"
  elasticconfiguration-username: "{{ .Values.elasticconfiguration_username }}"
  isapikeyenabled: "{{ .Values.isapikeyenabled }}"