# Default values for cep-module TEST.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: test
pvc:
  name: cep-module-test-pvc
  storage: 200Gi
  storageclassname: default
  mountfolder: "/Kafka"
  accessModes: ReadWriteOnce

resources:
  requests:
    cpu: 1
    memory: 16Gi
  limits:
    cpu: 8
    memory: 16Gi

# ingress controls
ingress:
  name: cep-module-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: qa-kz-cdp-cep-module-local.hostname.com
  secretName: hostname-wildcard-tls-cdp-tes-int-ns
  path: "/"
  className: internal-nginx

image:
  repository: cemulkerefe/cep-module
  tag: latest

kafka_bootstrap_server: kafka-cluster-test-kafka-bootstrap.cdp-test-kafka.svc:9092
cci_os_url: http://cdp-service-svc-test.cdp-test-app.svc:5500
elasticconfiguration_uri: "https://elk-qa.es.westeurope.azure.elastic-cloud.com:443"
elasticconfiguration_username: "logger"
elasticconfiguration_password: "password"
elasticconfiguration_kb_uri: "https://elk-qa.kb.westeurope.azure.elastic-cloud.com:443"
elasticconfiguration_kb_username: "logger"
elasticconfiguration_kb_password: "password"
isapikeyenabled: "true"
fletum_api_url: "https://fletum-test-api.azurewebsites.net"
thread_count: 12
thread_capacity: 10000

new_relic_app_name:
new_relic_license_key:

livenessProbe:
  enabled: true
  httpGet:
    path: "/swagger-ui.html"
    port: 7070
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
readinessProbe:
  enabled: true
  httpGet:
    path: "/swagger-ui.html"
    port: 7070
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
