# Default values for csv-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common controls
environment: dev
application: cep-module
containerPort: 7070
size: large

# Service controls
service:
  name: cep-module-svc
  type: ClusterIP
  port: 7070

hpa:
  enabled: false
  min: 1
  max: 1
  cpu: 95
  memory: 95

pvc:
  name: cep-module-dev-pvc
  storage: 2Gi
  storageclassname: default
  mountfolder: "/Kafka"
  accessModes: ReadWriteMany

# ingress controls
ingress:
  name: cep-module-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: cep-module-dev.11.11.111.111.nip.io
  secretName: cep-module-tls
  path: "/"

# Deployment controls
restartPolicy: Always

replicas: 1
resources:
  requests:
    cpu: 150m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi

image:
  imagePullSecret: regcred
  pullPolicy: Always
  repository: cemulkerefe/cep-module
  tag: latest

kafka_groupid: cep-group-1
country: kz
product_name: cdp
app_name: cep-module

new_relic_license_key:
logcustomerid: efectura
logproductname: cdp
logcountry: kz
logcomponentname: module
logapplicationname: cep

# liveness-readness
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

registrySecret:
  name: acr-registry
  config: { "auths": { "docker.io": { "auth": "" } } }
