# Default values for item-service DEV.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: dev

# ingress controls
ingress:
  name: item-service-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: dev-kz-cdp-item-service-local.hostname.com
  secretName: hostname-wildcard-tls-cdp-dev-int-ns
  path: "/"
  className: internal-nginx

image:
  repository: cemulkerefe/item-service
  tag: dev
  pullPolicy: Always

applicationinsights_instrumentationkey: 00000-0000-0000-0000-e0273a105a61
elasticconfiguration_uri: "elk-dev.es.westeurope.azure.elastic-cloud.com"
elasticconfiguration_username: "logger"
elasticconfiguration_password: "password"
isapikeyenabled: "true"
serilogminimumlevel: "Error"
fletum_api_url: "https://dev-fletum-api.azurewebsites.net"
connection_string: "Data Source=11.111.11.111;Initial Catalog=CDPDev;Persist Security Info=True;User ID= cdpdevuser;Password=123456;MultipleActiveResultSets=True;Application Name=item-service-dev"
validation_service_url: "http://validation-service-svc-dev.cdp-dev-app.svc:8010/api/"

logminimumlevel: INFO
new_relic_app_name:
new_relic_license_key:

livenessProbe:
  enabled: true
  httpGet:
    path: "/swagger/index.html"
    port: 8090
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
readinessProbe:
  enabled: true
  httpGet:
    path: "/swagger/index.html"
    port: 8090
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
