# Default values for item-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common controls
environment: dev
application: item-service
containerPort: 8090
size: large

# Service controls
service:
  name: item-service-svc
  type: ClusterIP
  port: 8090

hpa:
  min: 5
  max: 10
  cpu: 75
  memory: 75

# ingress controls
ingress:
  name: item-service-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: item-service-dev.11.11.111.111.nip.io
  secretName: item-service-tls
  path: "/"

# Deployment controls
restartPolicy: Always

replicas: 1
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1500m
    memory: 7Gi

image:
  imagePullSecret: regcred
  repository: cemulkerefe/item-service
  pullPolicy: Always
  tag: latest

country: KZ
product_name: CDP
app_name: item-service

# queue configurations
queue_delay: 1000
queue_size: 500

# ConfigMap controls
urls: http://0.0.0.0:8090

new_relic_license_key:
elasticconfiguration_port: 443
elasticconfiguration_scheme: https
logcustomerid: efectura
logproductname: cdp
logcountry: kz
logcomponentname: service
logapplicationname: item

# liveness-readness
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

registrySecret:
  name: acr-registry
  config: { "auths": { "docker.io": { "auth": "" } } }
