# Default values for item-service PREPROD.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: kz-preprod

resources:
  requests:
    cpu: 1500m
    memory: 4Gi
  limits:
    cpu: 1500m
    memory: 4Gi

# ingress controls
ingress:
  name: item-service-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key,token"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: preprod-kz-cdp-item-service-local.hostname.com
  secretName: hostname-wildcard-tls-preprod-integration-ns
  path: "/"
  className: internal-nginx

image:
  repository: cemulkerefe/item-service
  tag: latest

applicationinsights_instrumentationkey: 00000-0000-0000-0000-e0273a105a61
elasticconfiguration_uri: "elk-preprod.es.westeurope.azure.elastic-cloud.com"
elasticconfiguration_username: "logger"
elasticconfiguration_password: "0080000H0000x"
isapikeyenabled: "false"
serilogminimumlevel: "Error"
fletum_api_url: "https://preprod-api.azurewebsites.net"
connection_string: "Data Source=11.111.11.111;Initial Catalog=CDPKZPreProd;Persist Security Info=True;User ID= cdppreproduser;Password=123456;MultipleActiveResultSets=True;Application Name=item-service-dev"
validation_service_url: "http://validation-service-svc-preprod.cdp-preprod-app.svc:8010/api/"

logminimumlevel: INFO
new_relic_app_name: item-service-kz-preprod

livenessProbe:
  enabled: true
  httpGet:
    path: "/swagger/index.html"
    port: 8090
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
readinessProbe:
  enabled: true
  httpGet:
    path: "/swagger/index.html"
    port: 8090
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
