# Default values for api-gateway DEV.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: dev

# ingress controls
ingress:
  name: api-gateway-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: dev-kz-cdp-api-gw-local.hostname.com
  secretName: hostname-wildcard-tls-cdp-dev-app-ns
  path: "/"
  className: internal-nginx

image:
  repository: cemulkerefe/api-gateway
  imagePullSecret: regcred
  tag: 2.6.14

elasticconfiguration_uri: "elk.azure.elastic-cloud.com"
elasticconfiguration_username: "logger"
elasticconfiguration_password: "password"
applicationinsights_instrumentationkey: 9ca0a7d2-1234-1234-1234-e0273a105a61
isapikeyenabled: "true"

livenessProbe:
  enabled: true
  httpGet:
    path: "/swagger/index.html"
    port: 9201
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
readinessProbe:
  enabled: false

logminimumlevel: INFO
new_relic_app_name:
new_relic_license_key:
