# Default values for api-gateway PREPROD.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: kz-preprod

# ingress controls
ingress:
  name: api-gateway-ing
  clusterIssuer: letsencrypt
  allowCredentials: "true"
  allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SessionId,api-key"
  allowMethods: "*"
  allowOrigin: "*"
  enableCors: "true"
  hostName: preprod-kz-cdp-api-gw-local.hostname.com
  secretName: hostname-wildcard-tls-preprod-app-ns
  path: "/"
  className: internal-nginx

image:
  repository: cemulkerefe/api-gateway
  tag: 2.6.11

elasticconfiguration_uri: "elk-preprod.es.westeurope.azure.elastic-cloud.com"
elasticconfiguration_username: "logger"
elasticconfiguration_password: "password"
applicationinsights_instrumentationkey: b074fc6a-1234-1234-1234-4911669795d8
isapikeyenabled: "false"

hpa:
  min: 1
  max: 5
  cpu: 75
  memory: 75

livenessProbe:
  enabled: true
  httpGet:
    path: "/swagger/index.html"
    port: 9201
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
readinessProbe:
  enabled: true
  httpGet:
    path: "/swagger/index.html"
    port: 9201
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1

logminimumlevel: INFO
new_relic_app_name: api-gw-service-kz-preprod
